version: '3.8'

services:
  web-app:
    image: nginx:1.25-alpine
    container_name: web-container
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - web-network

networks:
  web-network:
    external: true